-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
    -   id: check-docstring-first
    -   id: check-json
    -   id: debug-statements
-   repo: https://github.com/pre-commit/pre-commit.git
    rev: v2.4.0
    hooks:
    -   id: validate_manifest
-   repo: https://gitlab.com/pycqa/flake8
    rev: "ee7081c8"
    hooks:
    -   id: flake8
